version: '3'

services:
  mariadb:
     container_name: mariadb
     networks:
       - inception
     build:
       context: requirements/mariadb
       dockerfile: Dockerfile
     env_file: .env
     volumes:
       - mariadb:/var/lib/mysql
     restart: always
     expose:
       - "3306"

  wordpress:
     container_name: wordpress
     env_file: .env
     volumes:
       - wordpress:/var/www/html
     networks:
       - inception
     build:
       context: requirements/wordpress
       dockerfile: Dockerfile
     depends_on:
       - mariadb
     restart: always
     expose:
       - "9000"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: always
 
volumes:
   wordpress:
     driver: local
     driver_opts:
       type: none
       o: bind
       device: /home/martin/data/wordpress
   mariadb:
     driver: local
     driver_opts:
       type: none
       device: /home/martin/data/mariadb
       o: bind
 
networks:
   inception:
     driver: bridge
